name: Continuous Integration and Synchronization
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - develop

jobs:
  quality:
    name: Check quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Checking
        run: npm run lint && npm run lint:type && npm run lint:eslint && npm run lint:prettier

  sync:
    name: Sync forked repo
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'

    steps:
      - name: Checkout develop
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.AUTO_ACTIONS }}
          fetch-depth: 0
          ref: develop

      - name: Add remote-url
        run: |
          git remote add forked-repo https://lgrin-byte:${{ secrets.AUTO_ACTIONS }}@github.com/lgrin-byte/nextRoomFE
          git config user.name lgrin-byte
          git config user.email ${{ secrets.EMAIL }}

      - name: Push changes to forked-repo
        run: |
          git push -f forked-repo develop

      - name: Clean up
        run: |
          git remote remove forked-repo
